#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $DB_USERNAME WITH LOGIN PASSWORD '$DB_PASSWORD';
    ALTER USER $DB_USERNAME CREATEDB;
    GRANT ALL PRIVILEGES ON SCHEMA public TO $DB_USERNAME;
    CREATE DATABASE $DB_DATABASE WITH OWNER $DB_USERNAME;
EOSQL

psql -U $DB_USERNAME -d $DB_DATABASE