# Stage 1: Build
FROM node:lts AS builder

WORKDIR /app

# Copy root package.json, turbo.json package-lock
COPY package.json turbo.json package-lock.json ./ 

# Install turbo and dependencies
RUN npm install -g turbo
RUN turbo install

# Copy the React app into the container
COPY apps/react-app ./apps/react-app 

# Debugging steps
RUN ls -l /app/apps/react-app
RUN cat /app/apps/react-app/package.json

# Install React app dependencies
RUN cd apps/react-app && npm install
# RUN cd apps/react-app

# Build the React app
RUN cd apps/react-app && turbo run build

# Stage 2: Run
FROM nginx:alpine

# Copy the build output to replace the default nginx contents.
COPY --from=builder /app/apps/react-app/build /usr/share/nginx/html

# Replace the default nginx config
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copy SSL certificates
COPY ./certs /etc/nginx/certs


# Expose port 80
EXPOSE 443

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
